### PR TITLE
Nestjs passport

### PR DESCRIPTION
**Pull request by Thorbenl**
Not sure how to continue with this.. we need to talk about a strategy :) i like this approach, but it doesnt fit our user/account/mess model, so we would have to adjust it/redo it :)

Please give me your input, on what we should do. 

Also, there is some config for GraphQL i copied from my old project, but its commented out here, but should be easy to add.

### CODE REVIEW

**Review by Xetera — APPROVED** [review]

**Comment by Xetera** [comment]
sorry I added a lot of conflicts to this, do u want me to merge these for u?

**Comment by Thorbenl** [comment]
> sorry I added a lot of conflicts to this, do u want me to merge these for u?

Lets maybe do it together? :) Would be fun! Im ok with VC :D 

But maybe lets discuss this, before moving forward. the auth with discord is working, but we cant do anything with it, since we cant save the user, because our user and accounts are so vastly different, so I would like to change it, and have one user model, and a new session model (as per this pr)

What do you think?

I think we will benefit in the sense that we can start nicely from scratch, and clean up a lot of (maybe) unused code. As someone not too familiar with accounts and users, this seems a little messy :( 

I can understand if you dont want this, since you have put time and effort into this, which ofc I do not forget when proposing these changes. I just see a bright future for Kiyomi and we should clean up while we essentially can, right now.

**Comment by Xetera** [comment]
I mean we need to change the way we do auth regardless because the previous system was bound to nextjs. In that sense we can do whatever changes we need to do to users and accounts and might even need to start from scratch which I'm okay with but I feel like we should be using passport because of how much more convenient it makes things.

We can talk about what issues you're having with passport in vc later maybe?

**Comment by Thorbenl** [comment]
> I mean we need to change the way we do auth regardless because the previous system was bound to nextjs. In that sense we can do whatever changes we need to do to users and accounts and might even need to start from scratch which I'm okay with but I feel like we should be using passport because of how much more convenient it makes things.
> 
> We can talk about what issues you're having with passport in vc later maybe?

We should and ARE using passport. However, in order to make serialisation make sense, we need to modify the user model a bit, since is has information different than what passport expect (id in passport are ints, and in our system strings, or vice versa)

Also we should be able to update/create a user in our db, when they log in with discord, which is also not possible, because we need to use `upsert` with enough data which we dont have available in passport.

Bascially: Our user model has too much data and types that dont match passports user/profile data :)

**Comment by Thorbenl** [comment]
@Xetera T_T can you resolve these conflicts?

**Pull request merged**
